### ISSUE TITLE
why use peerDependencies ?

### ISSUE THREAD

**Issue by lili21** [standard/eslint-config-standard#107]
why not just `npm install eslint-config-standard`

**Comment by feross** [comment]
I'd love to do this, but eslint shareable configs (which is what this package is) cannot contain executable code. It's just exporting a JavaScript object from a JSON file.

The **user** of the config is responsible for installing ESLint, the appropriate plugin dependencies, and instantiating ESLint with them.

So, the appropriate relationship to these dependencies is a peerDependency, not a normal one. If you're interested, you can read the issue about it here: https://github.com/eslint/eslint/issues/3458
