### ISSUE TITLE
Configuration for rule "indent" is invalid: Value "[object Object]" should NOT have additional properties.

### ISSUE THREAD

**Issue by booxood** [standard/eslint-config-standard#109]
"eslint": "^4.18.1",
    "eslint-config-standard": "^11.0.0",

**Comment by joeLepper** [comment]
Seeing the same failures with `eslint-config-standard@11.0.0` and `eslint@3.19.0`

Didn't see it at `eslit-config-standard@11.0.0-beta.0` and `eslint@3.19.0`

**Comment by feross** [comment]
@joeLepper It's not expected to work with `eslint@3` since the indent rules got stricter in `eslint@4` and we took the opportunity to specify them fully after that beta version you're using.

**Comment by feross** [comment]
@booxood Can you share the output of `npm ls --depth=9999 eslint`?

**Comment by joeLepper** [comment]
Noted. Thanks.

**Comment by booxood** [comment]
@feross 

```
├── eslint@4.18.1 
└─┬ react-scripts@1.1.1
  └── eslint@4.10.0 
```

**Comment by webdevian** [comment]
This fails for me when running via gulp-eslint. My npm output is 
```
├─┬ apc-build@0.4.2
│ └─┬ gulp-eslint@4.0.2
│   └── eslint@4.13.1 
└─┬ apc-style@1.1.0
  ├─┬ eslint-config-apc@1.1.0
  │ └── eslint@4.18.1 
  └─┬ sass-lint@1.12.1
    └── eslint@2.13.1 
```

**Comment by webdevian** [comment]
Deleting and re-generating my yarn lock file has solved this: 

```
octopus@0.1.0 /Users/iegner/Code/octopus
├─┬ apc-build@0.4.2
│ └─┬ gulp-eslint@4.0.2
│   └── eslint@4.18.1 
└─┬ apc-style@1.1.0
  ├─┬ eslint-config-apc@1.1.0
  │ └── eslint@4.18.1  deduped
  └─┬ sass-lint@1.12.1
    └── eslint@2.13.1 
```

**Comment by feross** [comment]
@booxood It seems the eslint from `react-scripts` is somehow being used instead of the one that you explicitly installed at version 4.18.1. Without knowing more about your specific setup, it's not clear how to help you.

There is no bug with this eslint shareable configuration, so I'm going to close this issue.

**Comment by feross** [comment]
@webdevian It doesn't appear that you're actually using standard.

**Comment by booxood** [comment]
@feross `eslint@4.10.0` do not support this `indent` configuration?

**Comment by booxood** [comment]
I create a [repo](https://github.com/booxood/eslint-config-standard-demo) for reproduce the problem.

**Comment by webdevian** [comment]
@feross eslint-config-apc has standard as a dependency

**Comment by joeyvandijk** [comment]
I had multiple times this error and it always had to do that I did not have the latest eslint package, but an older which provided the same error. `npm i eslint@latest` and this error vanishes because it probably is again in sync with the latest features eslint provides.

**Comment by pei-han** [comment]
@booxood  这个问题你是如何解决的？

**Comment by booxood** [comment]
@pei-han 换版本

**Comment by pei-han** [comment]
@booxood 的确如此，我按照@joeyvandijk的方法，解决问题。
看来是新版的eslint中rule才支持的属性吧。

@joeyvandijk  thanks so much

**Comment by nikoladev** [comment]
I have this same issue because of `react-scripts` too. For anybody that has this same issue and is using VS Code with the [ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) you can add the following to your workspace settings:

```json
{
  "eslint.nodePath": "./node_modules/standard/node_modules/eslint/",
}
```

This will ensure the extension uses the version of ESLint that standard expects.
