### ISSUE TITLE
can not find module eslint-configura-standard 

### ISSUE THREAD

**Issue by gogoIsComing** [standard/eslint-config-standard#110]
hey guys :
i have installed :
eslint extension globally using 
`npm install elsint -g`
`eslint --init`

and i get this error and i don not know way :
![1](https://user-images.githubusercontent.com/33967218/37003277-316a17b8-20d5-11e8-9b23-8671c7291691.png)

.eslintrc.js file :
![2](https://user-images.githubusercontent.com/33967218/37003300-47e9c20e-20d5-11e8-997f-4a6d257b0df6.png)

package.json file :
![3](https://user-images.githubusercontent.com/33967218/37003322-56ad51f2-20d5-11e8-8604-bc4e2c9c2be0.png)

Any Help :)

**Comment by feross** [comment]
You installed eslint globally (using `npm install -g`) but you installed `eslint-config-standard` locally. That won't work.

Either install them all globally or all locally.

I recommend adding `eslint` as a local dependency and then running it with `npx eslint`.
