### ISSUE TITLE
Cannot find module 'eslint-config-standard'

### ISSUE THREAD

**Issue by portedison** [standard/eslint-config-standard#113]
Apologies, I have seen a few issues that reference this same error, but the solution for those seemed to be a mismatch between global/local installations. However I've installed using the following.
```
npm i -g eslint eslint-plugin-standard eslint-plugin-import \
eslint-plugin-node eslint-plugin-promise eslint-config-standard \
eslint-config-semistandard
```
All packages are global within `/usr/local/lib/node_modules` and running `npm config get prefix` gives me `/usr/local` which I've included in eslint's settings global node installation path.

**Comment by portedison** [comment]
Fixed. Needed to check Use global ESLint installation. Worth adding to the docs for global install?

**Comment by Shuunen** [comment]
On https://eslint.org/docs/user-guide/getting-started it says : 

> It is also possible to install ESLint globally rather than locally (using npm install eslint --global). However, any plugins or shareable configs that you use must be installed locally in either case.

So @feross do you confirm it's not possible to use eslint-config-standard globally ?

@portedison I don't understand how you managed to succeed ?

**Comment by feross** [comment]
ESLint 6 changed the way that this works. Previously it was possible to install ESLint, as well as the configs and plugins all globally and it would work. Now, as the readme says, you can install ESLint globally, but you still need to install any plugins or shareable configs locally, so there's really not much reason to do a global install.
