### ISSUE TITLE
Warning message with ESLint 5

### ISSUE THREAD

**Issue by ehmicky** [standard/eslint-config-standard#114]
When used with ESLint `5.0.0-alpha.2`, this ESLint config produces the following warning message:
```
[ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "standard")
```

This is due to https://github.com/eslint/eslint/pull/10230

**Comment by feross** [comment]
Thanks for the issue.

I just published `eslint-config-standard@12.0.0-alpha.0` that you can use with  ESLint 5. Be warned that there are going to be npm install warnings until all the ESLint plugins we use also update their `peerDependencies` to support `eslint@5.0.0-alpha.2`.

Get it with `npm install eslint-config-standard@next`

**Comment by unindented** [comment]
@feross is there anything blocking the release of `12.0.0` proper?

**Comment by voxpelli** [comment]
@unindented see #123, nothing really blocking (apart from an action from the maintainers), but a few things that are nice to haves

**Comment by corysimmons** [comment]
Not sure if it's on anyone's radar but these also need updating in:

- standard-react
- eslint-config-standard-jsx
