### ISSUE TITLE
"no-console" Rule

### ISSUE THREAD

**Issue by palme1337** [standard/eslint-config-standard#141]
Is there any reason there is no "no-console" rule in the js standard ruleset? Is there a way to add our own custom rule for this particular case? It would help reduce some annoyance in thinkos where developers leave them in the code. 

Thank you.

**Comment by begueradj** [comment]
It there set off by default.

**Comment by feross** [comment]
You can override rules by adding `"rules"` to your `.eslintrc` file:

```json
{
  "extends": "standard",
  "rules": {
    "no-console": "off"
  }
}

**Comment by feross** [comment]
Oh, I just realized this issue makes no sense! We don't enable `no-console`, as @begueradj pointed out :)

**Comment by LinusU** [comment]
> Is there any reason there is **no** "no-console" rule in the js standard ruleset?

They were asking for us to add it ☺️ 

I personally prefer not to since there are plenty of valid use cases for `console.log` other than sprinkling them temporary to debug things...

**Comment by mightyiam** [comment]
`console` is an output side effect. Happens to be the one that is used for debugging, as well. We can't really tell whether it's for debugging...

**Comment by feross** [comment]
> They were asking for us to add it ☺️

Sheesh, I need to read more slowly :)
