### ISSUE TITLE
eslint-plugin-standare error

### ISSUE THREAD

**Issue by sreenivasulu509** [standard/eslint-config-standard#142]
Server listening on 0.0.0.0:3000
  ████████████████████ 15% building modules(node:20828) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "standard")
  ████████████████████ 20% building modules{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
  █████████████

**Comment by mikegioia** [comment]
I'm seeing this too, but just on linting:

```
(node:26274) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "standard")
```

**Comment by feross** [comment]
It sounds like you're using an old version of `standard`. We haven't used the `experimentalObjectRestSpread` option for a while.
