### ISSUE TITLE
vue and nutx js libraries issue

### ISSUE THREAD

**Issue by sreenivasulu509** [standard/eslint-config-standard#143]
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN terser-webpack-plugin@1.2.3 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.

audited 892565 packages in 26.493s
found 13 vulnerabilities (5 moderate, 8 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by feross** [comment]
This is not an issue with this package.
