### ISSUE TITLE
Failed to load plugin 'standard' declared in 'CLIOptions'

### ISSUE THREAD

**Issue by llucasmota** [standard/eslint-config-standard#147]
6/30/2019, 10:00:02 AM:
-----------------------
Failed to load plugin 'standard' declared in 'CLIOptions' {my_path}:: Cannot find module 'eslint-plugin-standard'
Require stack:
- /__placeholder__.js

**Comment by voxpelli** [comment]
I think there are some more details needed than that @llucasmota, are you for example sure that you actually added the plugin? Are you using a local or a global ESLint? Which version of that ESLint?

**Comment by feross** [comment]
I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨
