### ISSUE TITLE
no-negated-in-lhs is deprecated in eslint

### ISSUE THREAD

**Issue by nathanBrenner** [standard/eslint-config-standard#157]
**What version of this package are you using?**
Not currently using, but about to import this into a project to replace a lot of the existing rules that are part of this 
**What operating system, Node.js, and npm version?**
node: 10.16.0, npm: 6.9.0, os: macOs Mojave 10.14.6
**What happened?**
From reading https://github.com/standard/eslint-config-standard/blob/master/eslintrc.json and https://eslint.org/docs/rules/#deprecated no-negated-in-lhs has been deprecated and replaced with  no-unsafe-negation
**What did you expect to happen?**
The rules stay up to date with latest version of eslint
**Are you willing to submit a pull request to fix this bug?**
yes

**Comment by feross** [comment]
Fixed by #158
