### ISSUE TITLE
show the wrong error notice about javascript files

### ISSUE THREAD

**Issue by Wayne529** [standard/eslint-config-standard#161]
**What version of this package are you using?**
 "eslint-config-standard": "^14.1.0"

**What operating system, Node.js, and npm version?**
node.js is 10.18.0 and npm version is 6.13.4

**What happened?**
when i use this npm with eslint, it get something wrong to notice me the errors in the javascript file of my project.like this error:
  1:1  error  Definition for rule 'no-async-promise-executor' was not found      no-async-promise-executor
  1:1  error  Definition for rule 'no-misleading-character-class' was not found  no-misleading-character-class
  1:1  error  Definition for rule 'no-useless-catch' was not found               no-useless-catch
but the rules is used for Promise,not for the situation,my javascript is just es6 grammar like import/export.so i think it maybe a bug,because it get wrong notice.
I had view the update log of this,it add these rules above the 13.0 version.
so I turn off the rule in my eslintrc.js ,like this:
   'no-async-promise-executor' : 'off',
    'no-misleading-character-class' : 'off',
    'no-useless-catch' : 'off'

or i reload the npm of lower version.
it can works. the wrong notice is gone.

**What did you expect to happen?**
i want the correct notice,if it has no error,it should not show the error notice

**Are you willing to submit a pull request to fix this bug?**
no.

I wish the question can be resolved, tks!

**Comment by mightyiam** [comment]
Hi, @Wayne529 and thank you for using Standard. Could you please share the version of the package `eslint` in your project by running `$ npm ls eslint`?

**Comment by woowalker** [comment]
![image](https://user-images.githubusercontent.com/7894779/84868719-b6bfa600-b0af-11ea-9b84-997731c46af4.png)
got the same problem

**Comment by mightyiam** [comment]
@woowalker could I see the error, please?

**Comment by woowalker** [comment]
> @woowalker could I see the error, please?

![image](https://user-images.githubusercontent.com/7894779/88641891-5ed67f00-d0f2-11ea-836f-82a0a62a6dda.png)

![image](https://user-images.githubusercontent.com/7894779/88641977-79a8f380-d0f2-11ea-9492-8c3d918e170d.png)

sorry for late reply

**Comment by mightyiam** [comment]
[Documentation for rule `no-async-promise-executor` claims that it was added to ESLint in version 5.3.0](https://eslint.org/docs/rules/no-async-promise-executor#version).

You seem to have ESLint v4.

**Comment by woowalker** [comment]
means that upgrade ESLint to v5 can get rid of this error ? @mightyiam

**Comment by mightyiam** [comment]
@woowalker yes, it should.

**Comment by woowalker** [comment]
@mightyiam ok thanks
