### ISSUE TITLE
Parsing error: Invalid ecmaVersion error while running lint

### ISSUE THREAD

**Issue by jainanuj0812** [standard/eslint-config-standard#162]
**What version of this package are you using?**
14.1.0

**What operating system, Node.js, and npm version?**
Node :- 10.17.0
Npm :- 6.11.3

**What happened?**
linting fails getting following error

` 0:0  error  Parsing error: Invalid ecmaVersion`

**What did you expect to happen?**
should work fine

**Are you willing to submit a pull request to fix this bug?**

**Comment by mightyiam** [comment]
Could you please provide your eslint config file and eslint version?

**Comment by ravindra-clairvoyant** [comment]
@jainanuj0812, you might need to check [this ESlint blog](https://eslint.org/blog/2019/08/eslint-v6.2.0-released) if you are using a [eslint-config-standard](https://www.npmjs.com/package/eslint-config-standard) package version which uses `ecmaVersion` 2020 internally

update your [ESlint](https://www.npmjs.com/package/eslint) package to v6.2.0 or the latest and you should be able to get rid of this issue

**Comment by jainanuj0812** [comment]
@ravindra-clairvoyant Thanks!
