### ISSUE TITLE
14.1.1 not published to npm

### ISSUE THREAD

**Issue by LinusU** [standard/eslint-config-standard#165]
I didn't have publishing rights to `eslint-config-standard` on Npm so 14.1.1 is currently tagged and pushed to the repository, but not published to Npm.

@feross or @Flet, if one of you could add me to the package that would be great ☺️ 

@Flet not sure if you can add people or not, if not could you run `git checkout v14.1.1 && npm publish` so that the version gets published? thanks ❤️

**Comment by mightyiam** [comment]
I don't have permission, as well.

**Comment by feross** [comment]
@LinusU You now have permissions. Once we get the npm org set up this should hopefully no longer be an issue.

**Comment by LinusU** [comment]
Published ✔️
