### ISSUE TITLE
Release suggestion: 16.0.3

### ISSUE THREAD

**Issue by LinusU** [standard/eslint-config-standard#187]
I suggest that we make a quick release, 16.0.3, that relaxes the peer dependency to also include version 5.x of `eslint-plugin-promise` (https://github.com/standard/eslint-config-standard/commit/8fdbb4532f1521ec231d7b3ced887cc72685993d)

ping @Divlo @voxpelli if you give 👍 I'll cut a release now :shipit:

**Comment by Divlo** [comment]
:+1:

**Comment by LinusU** [comment]
Published :shipit:
