### ISSUE TITLE
Configuration for rule "no-unused-expressions" is invalid. Should NOT have additional properties.

### ISSUE THREAD

**Issue by jorgev259** [standard/eslint-config-standard#188]
**What version of this package are you using?** 
16.0.3

**What operating system, Node.js, and npm version?** 
Windows 10 64-bit, Node 16.6.0 and NPM 7.20.3

**What happened?**
Using this .eslintconfig, eslint errors with the message: Configuration for rule "no-unused-expressions" is invalid:
	Value {"allowShortCircuit":true,"allowTernary":true,"allowTaggedTemplates":true,"enforceForJSX":false} should NOT have additional properties.

```{
  "env": {
    "es2021": true,
    "node": true,
    "browser": true
  },
  "extends": [
    "standard",
    "plugin:react/recommended"  
  ],
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 12,
    "sourceType": "module"
  },
  "plugins": ["react"],
  "rules": {
    "react/jsx-uses-react": "off",
    "react/react-in-jsx-scope": "off",
    "react/prop-types": "off",
    "react/jsx-indent": [
      "error",
      2
    ]
  }
}```

**Comment by LinusU** [comment]
Hmm, all of those four options are listed in the official documentation:

https://eslint.org/docs/rules/no-unused-expressions#options

Could it be that your setup somehow pulls in an old version of ESLint? 🤔

**Comment by jorgev259** [comment]
Probably, seems to work fine on a clean install machine. Ill reopen if i bump into it again. 
Thanks.
