### ISSUE TITLE
eslint 8 compatibility

### ISSUE THREAD

**Issue by TrejGun** [standard/eslint-config-standard#192]
Hi guys!

Please tell us if `eslint-config-standard` is compatible with the new version of ESlint? 
and if yes please add it to peerDependencies

**Comment by voxpelli** [comment]
We are actively working towards this, yes! Though we have been a bit short of time lately, will try to get it out as soon as possible. See PR.

**Comment by meabed** [comment]
Thanks a lot @voxpelli - would this be ready anytime soon? I could help if needed to get it ready.

**Comment by voxpelli** [comment]
@meabed We are largely waiting for two of the plugins that we use (`eslint-plugin-node` and `eslint-plugin-promise`) to be updated to support ESLint 8, no ETA from the maintainers of those, we're tracking the status of it in #193 

Right now I don't think there's much to help with in that regard, but thanks for the offer! 🙏

**Comment by JanFellner** [comment]
The dependency eslint-config-node you refer to seems not widely used, it has weekly downloads of 36.104....
Do you *really* rely on it or would it be possible to drop that dependency?

**Comment by voxpelli** [comment]
> The dependency eslint-config-node you refer to seems not widely used, it has weekly downloads of 36.104.... Do you _really_ rely on it or would it be possible to drop that dependency?

It's the _plugin_ that we use, it has 3 million weekly downloads: https://www.npmjs.com/package/eslint-plugin-node 🙂

**Comment by JanFellner** [comment]
A might got guided into a wrong direction. This PR mentiones the config...
https://github.com/standard/eslint-config-standard/pull/193#issue-1021910367
"ehmicky mentioned this pull request on 11 Oct "
fix(deps): update dependency eslint to v8 netlify/eslint-config-node#321

**Comment by voxpelli** [comment]
@JanFellner It mentions the plugin? Only mention of `eslint-config-node` there is that they mention in a PR that they are blocked by us before they can upgrade to `ESLint 8`, as they depend on us: https://github.com/netlify/eslint-config-node/blob/ddd5fb1c482eb6fde48a354e4126a4297c2ddf72/.eslintrc.js#L12

**Comment by aladdin-add** [comment]
`eslint-plugin-node`'s latest version v11.1.0 was published ~2y ago. I've asked the author, but no response. :-( 

https://github.com/mysticatea/eslint-plugin-node/issues/300

**Comment by voxpelli** [comment]
@aladdin-add If you want help, we could check if we could bring your fork under the Standard organization.

Been pondering that a fork probably would be necessary, great that you got around to do it!

**Comment by aladdin-add** [comment]
sure, I'm totally open to transferring to Standard, for better maintainability and discoverability.

**Comment by aladdin-add** [comment]
another point: nicholas has a plan to make an org eslint-community. It's also great to go there (yes, eslint is its user too!). I'll talk to him to see what's his suggestion.

**Comment by MichaelDeBoey** [comment]
Would be nice if we could transfer repos  like `eslint-plugin-node` to a new @eslint-community org

**Comment by MichaelDeBoey** [comment]
@xjamundx let me know that `eslint-plugin-promise` can be added to the new org too

CC/ @aladdin-add @voxpelli

**Comment by MichaelDeBoey** [comment]
@voxpelli @aladdin-add Do we already have some news about the new @eslint-community org and moving [`eslint-plugin-node`](https://github.com/mysticatea/eslint-plugin-node), [`eslint-plugin-es`](https://github.com/mysticatea/eslint-plugin-es), [`eslint-utils`](https://github.com/mysticatea/eslint-utils), [`@mysticatea/eslint-plugin`](https://github.com/mysticatea/eslint-plugin) & [`eslint-plugin-promise`](https://github.com/xjamundx/eslint-plugin-promise) over there?

It would be awesome if we could talk about this on Twitter or Discord or so.
https://twitter.com/MichaelDeBoey93

**Comment by voxpelli** [comment]
@MichaelDeBoey Are you in control of @eslint-community? If so, then feel free to add me there and we can have a discussion in a team we set up there?

**Comment by MichaelDeBoey** [comment]
@voxpelli I'm not, I thought one of you guys was tbh 🤔

I would like to be added too if possible.

**Comment by voxpelli** [comment]
@MichaelDeBoey Lets continue the discussion here: https://github.com/weiran-zsd/eslint-plugin-node/issues/8
