### ISSUE TITLE
16.0.3 still looking for eslint v7

### ISSUE THREAD

**Issue by rexkenley** [standard/eslint-config-standard#209]
**What version of this package are you using?**
16.0.3

**What operating system, Node.js, and npm version?**
windows 10, node 16.13.1, npm 8.1.2.

**What happened?**
![image](https://user-images.githubusercontent.com/10548251/148796401-82173254-633e-4519-a4f2-1b33411b8077.png)

**What did you expect to happen?**
Install the package

**Comment by Divlo** [comment]
Please see this issue: https://github.com/standard/eslint-config-standard/issues/208.

`eslint-config-standard@17.0.0-0` contains ESLint v8 support.
