### ISSUE TITLE
 Parsing error: This experimental syntax requires enabling one of the following parser plugin(s): 'jsx, flow, typescript'

### ISSUE THREAD

**Issue by ko-devHong** [standard/eslint-config-standard#268]
**What version of this package are you using?** 17.0.0

**What operating system, Node.js, and npm version?** 
node :v16.18.0
npm : 8.19.2

**What happened?**
I got  error `ESLint: Parsing error: This experimental syntax requires enabling one of the following parser plugin(s): 'jsx, flow, typescript' (2:9)`

**What did you expect to happen?**
it work

**Are you willing to submit a pull request to fix this bug?**

**Comment by ko-devHong** [comment]
I solved downgrade version `17.0.0` => `16.0.3`

**Comment by rostislav-simonik** [comment]
@ko-devHong can you provide a reproducible example
