### ISSUE TITLE
Peer dependency issue

### ISSUE THREAD

**Issue by wijkjh** [standard/eslint-config-standard#273]
**What version of this package are you using?**
17.0.0

**What operating system, Node.js, and npm version?**
Node.js 16.19, npm 9.3.1

**What happened?**
Upgrading to latest eslint-plugin-n 16.0.0 fails in an error:
```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: my-package@1.10.3
npm WARN Found: eslint-plugin-n@15.7.0
npm WARN node_modules/eslint-plugin-n
npm WARN   peer eslint-plugin-n@"^15.0.0" from eslint-config-standard@17.0.0
npm WARN   node_modules/eslint-config-standard
npm WARN     dev eslint-config-standard@"^17.0.0" from the root project
npm WARN   1 more (the root project)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-n@"^15.0.0" from eslint-config-standard@17.0.0
npm WARN node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"^17.0.0" from the root project 
```

package.json has already been updated, but version in package.json has not been updated, so there is no no release on npm yet.

**What did you expect to happen?**
It to be installed.
Without a new release on npm (with a new version), the package will prevent updating to a newer eslint-plugin-n version.

The version in package.json should be increased to a higher version and released to npm registry.

**Are you willing to submit a pull request to fix this bug?**
If needed

**Comment by voxpelli** [comment]
Fixed by #271 in `17.1.0`
