### ISSUE TITLE
update to eslint v4

### ISSUE THREAD

**Issue by balupton** [standard/eslint-config-standard#82]
http://eslint.org/docs/4.0.0/user-guide/migrating-to-4.0.0

eslint v4 is in alpha right now

for the most part, seems that this package works fine with it, but there are probably some rule upgrades that are worth doing to take full advantage of it

**Comment by LinusU** [comment]
> The indent rule is more strict

Hurray 🎉

**Comment by Flet** [comment]
Nice! I think it makes sense to let eslint v4 bake for a while before bringing i in :)

**Comment by voxpelli** [comment]
What do you think about the baking of eslint v4 now 2.5 months later? Battle tested enough to bring it in here?

**Comment by voxpelli** [comment]
@Flet A friendly reminder now 2 months later again :)

Is this perhaps blocked by https://github.com/standard/standard/issues/925 ? Or is it the other way around – that this is blocking that issue? Or is there no hard relation between the two

**Comment by Flet** [comment]
Thanks everyone for your patience :)

`eslint-config-standard@11.0.0-beta.0` is released, which updates to eslint v4. Please give it a try!

**Comment by Flet** [comment]
Oh, also it can be used directly via `standard`: `npm i -g standard@beta`
