### ISSUE TITLE
Move to eslint-plugin-node v5

### ISSUE THREAD

**Issue by Arcanemagus** [standard/eslint-config-standard#87]
[`eslint-plugin-node@5`](https://github.com/mysticatea/eslint-plugin-node/releases/tag/v5.0.0) and a few subsequent versions are out now, this configuration should be updated to take advantage of it.

**Comment by ematipico** [comment]
Yeah I think it's worth to upgrade the package

**Comment by Flet** [comment]
`eslint-config-standard@11.0.0-beta.0` has been published with this package updated.

Give it a shot!
