### ISSUE TITLE
currently in v10.2.1 but no changelog available

### ISSUE THREAD

**Issue by Floby** [standard/eslint-config-standard#88]
At the time of writing of this issue this package has version 10.2.1 but the official changelog (which is the one for standardjs) only goes up to 10.0.3 (2017-08-06). This incidentally brings quite a lot of errors on my existing codebase, most notably regarding indentation.

I feel there should be one of two things:
+ a Changelog up to 10.2.1
+ a `beta` or `unstable` tag on the published versions above 10.0.3

**Comment by Flet** [comment]
The [commit history](https://github.com/standard/eslint-config-standard/commits/master) should help sort out whats specifically been released for this package.

 The latest version of `standard` uses the latest 10.2.1 version of this package (check it out in [standard's package.json](https://github.com/standard/standard/blob/master/package.json#L16))
The versioning of this package is mostly independent of the versioning on `standard` (we try to keep the major version in sync these days).

**Comment by Floby** [comment]
Ok thank you for the clarification. Turns out it was mostly the update of eslint itself that caused so much trouble with indentations.
