### ISSUE TITLE
Mention eslint --init in documentation

### ISSUE THREAD

**Issue by nickmccurdy** [standard/eslint-config-standard#92]
I recently discovered that `eslint --init` can automatically create a config extending this config if you choose `Standard` under `Use a popular style guide`. This also automatically installs `peerDependencies`, and I personally find it more convenient than the manual approach that's currently in the readme.

**Comment by Flet** [comment]
Nice!

**Comment by feross** [comment]
Yes, this is a great idea. Does someone want to try sending a PR to solve this? Happy to review and merge the PR!
