### ISSUE TITLE
Do not specify parserOptions

### ISSUE THREAD

**Issue by mightyiam** [standard/eslint-config-standard#95]
In the case that I wish to use a different parser, like `typescript-eslint-parser`, for example, the provided `parserOptions` might conflict. And [they do](https://github.com/eslint/typescript-eslint-parser/issues/392#issuecomment-338494371).

Would it be OK if we specify these `parserOptions` somewhere else? Perhaps in the `standard-engine` package, instead of here?

**Comment by feross** [comment]
Moving this option out of this config at this point would break everyone depending on `eslint-config-standard` directly and I don't think it's worth the churn. Can you continue to use whatever workaround you're currently using?
