### ISSUE TITLE
Not displaying any errors for me

### ISSUE THREAD

**Issue by vjsingh** [standard/eslint-config-standard#96]
Had trouble installing this because my eslint was global, but I was installing eslint-config-standard locally. It was even more complicated because I use Syntastic which wasn't showing me the errors.

May be worth adding to the description? I can't be the only one =)

Fixed by finding this issue: https://github.com/standard/eslint-config-standard/issues/84

**Comment by Flet** [comment]
Yeah, this could be a good note to add. PR welcome!

**Comment by feross** [comment]
@vjsingh PR still welcome to add this!
