### ISSUE TITLE
Does not seem to be compatible with plugin rules

### ISSUE THREAD

**Issue by arctelix** [standard/eslint-config-standard#97]
I am trying to use the following config.
 ```JSON
{
    "parserOptions": {
      "ecmaVersion": 6,
      "sourceType": "module",
      "ecmaFeatures": {
        "jsx": true,
        "modules": true
      }
    },
    "extends": "standard",
    "plugins": [
      "react",
      "chai-friendly",
      "mocha"
    ],
    "rules": {
      "no-unused-expressions": 0,
      "chai-friendly/no-unused-expressions": 2,
      "mocha/no-exclusive-tests": "error"
    }
}
```
When extending `stadard` it does not respect the plugin rules.  For example, i'm getting `describe is not defined`.  If I remove `extends: "standard"` from the config the error goes away.

**Comment by LinusU** [comment]
This is just a guess, but could it be that the `no-undef` wasn't enabled earlier? It seems to me like only three rules are enabled before extending standard, but I'm not 100% sure on how plugins works.

I would personally recommend adding `/* eslint-env mocha */` to the top of your test files, that will tell eslint that `describe`, `it`, etc. are global variables, and won't complain when you are using them.

**Comment by feross** [comment]
You can fix this error by explicitly disabling the rule that the `standard` config is enabling ([`no-undef`](https://eslint.org/docs/rules/no-undef)). Just add `"no-undef": 0` to your `"rules"` section.
